FROM node:20-slim

WORKDIR /app

# Копируем package файлы
COPY package*.json ./

# Устанавливаем только production зависимости
RUN npm ci --omit=dev

# Копируем весь код
COPY . .

# Запускаем миграции
CMD ["npm", "run", "migrate"]